{
  "cells": [
    {
      "cell_type": "markdown",
      "id": "be88907a",
      "metadata": {
        "id": "be88907a"
      },
      "source": [
        "## Portfolio 1\n",
        "\n",
        "Wij hebben als spel 4 op een rij gekozen."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "a617ccc6",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "a617ccc6",
        "outputId": "3dc57a0e-8a3f-4a7b-b645-51f518c1455f"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting pettingzoo\n",
            "  Downloading pettingzoo-1.25.0-py3-none-any.whl.metadata (8.9 kB)\n",
            "Collecting chess\n",
            "  Downloading chess-1.11.2.tar.gz (6.1 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.1/6.1 MB\u001b[0m \u001b[31m99.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Requirement already satisfied: pygame in /usr/local/lib/python3.12/dist-packages (2.6.1)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)\n",
            "Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (6.17.1)\n",
            "Requirement already satisfied: gymnasium>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pettingzoo) (1.2.3)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)\n",
            "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)\n",
            "Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (1.8.15)\n",
            "Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (7.34.0)\n",
            "Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (7.4.9)\n",
            "Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (0.2.1)\n",
            "Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel) (1.6.0)\n",
            "Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel) (5.9.5)\n",
            "Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (26.2.1)\n",
            "Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (6.5.1)\n",
            "Requirement already satisfied: traitlets>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel) (5.7.1)\n",
            "Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium>=1.0.0->pettingzoo) (3.1.2)\n",
            "Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium>=1.0.0->pettingzoo) (4.15.0)\n",
            "Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from gymnasium>=1.0.0->pettingzoo) (0.0.4)\n",
            "Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel) (75.2.0)\n",
            "Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel)\n",
            "  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)\n",
            "Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel) (4.4.2)\n",
            "Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel) (0.7.5)\n",
            "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel) (3.0.52)\n",
            "Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel) (2.19.2)\n",
            "Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel) (0.2.0)\n",
            "Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel) (4.9.0)\n",
            "Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel) (0.4)\n",
            "Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel) (5.9.1)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)\n",
            "Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.6)\n",
            "Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel) (4.9.4)\n",
            "Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel) (0.7.0)\n",
            "Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel) (0.6.0)\n",
            "Downloading pettingzoo-1.25.0-py3-none-any.whl (852 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m852.5/852.5 kB\u001b[0m \u001b[31m51.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.6/1.6 MB\u001b[0m \u001b[31m74.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hBuilding wheels for collected packages: chess\n",
            "  Building wheel for chess (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for chess: filename=chess-1.11.2-py3-none-any.whl size=147775 sha256=4e44acf2e29817be2568d48aa20b7969f0daf4fd31b4104befc30c99bacf30b5\n",
            "  Stored in directory: /root/.cache/pip/wheels/83/1f/4e/8f4300f7dd554eb8de70ddfed96e94d3d030ace10c5b53d447\n",
            "Successfully built chess\n",
            "Installing collected packages: jedi, chess, pettingzoo\n",
            "Successfully installed chess-1.11.2 jedi-0.19.2 pettingzoo-1.25.0\n"
          ]
        }
      ],
      "source": [
        "import sys\n",
        "!\"{sys.executable}\" -m pip install pettingzoo chess pygame numpy matplotlib ipykernel"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "3b9f1dff",
      "metadata": {
        "id": "3b9f1dff"
      },
      "outputs": [],
      "source": [
        "from pettingzoo.classic import connect_four_v3"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "da051882",
      "metadata": {
        "id": "da051882"
      },
      "outputs": [],
      "source": [
        "env = connect_four_v3.env(render_mode=\"human\")\n",
        "env.reset()\n",
        "\n",
        "for agent in env.agent_iter():\n",
        "\n",
        "    observation, reward, termination, truncation, info = env.last()\n",
        "\n",
        "    if termination or truncation:\n",
        "        action = None\n",
        "    else:\n",
        "        mask = observation[\"action_mask\"]\n",
        "\n",
        "        # kies eerste geldige zet\n",
        "        legal_moves = [i for i, m in enumerate(mask) if m == 1]\n",
        "        action = legal_moves[0]\n",
        "\n",
        "    env.step(action)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "d1fa3b33",
      "metadata": {
        "id": "d1fa3b33"
      },
      "outputs": [],
      "source": [
        "import numpy as np\n",
        "import random\n",
        "\n",
        "class BlockingAgent:\n",
        "\n",
        "    def act(self, observation):\n",
        "\n",
        "        board = observation[\"observation\"]\n",
        "        mask = observation[\"action_mask\"]\n",
        "\n",
        "        legal_moves = [i for i, m in enumerate(mask) if m == 1]\n",
        "\n",
        "        opponent = board[:, :, 1]\n",
        "\n",
        "        # 🔥 check elke kolom: voorkomt directe winst\n",
        "        for col in legal_moves:\n",
        "\n",
        "            row = self.get_next_open_row(opponent, col)\n",
        "            if row is None:\n",
        "                continue\n",
        "\n",
        "            temp_board = opponent.copy()\n",
        "            temp_board[row][col] = 1\n",
        "\n",
        "            if self.check_win(temp_board):\n",
        "                print(\"BLOCKING WIN:\", col)\n",
        "                return col\n",
        "\n",
        "        # 🔥 extra: detecteer 3-op-een-rij dreigingen\n",
        "        for col in legal_moves:\n",
        "\n",
        "            row = self.get_next_open_row(opponent, col)\n",
        "            if row is None:\n",
        "                continue\n",
        "\n",
        "            if self.creates_threat(opponent, row, col):\n",
        "                print(\"BLOCKING THREAT:\", col)\n",
        "                return col\n",
        "\n",
        "        return random.choice(legal_moves)\n",
        "\n",
        "    def get_next_open_row(self, board, col):\n",
        "        for row in reversed(range(6)):\n",
        "            if board[row][col] == 0:\n",
        "                return row\n",
        "        return None\n",
        "\n",
        "    def check_win(self, board):\n",
        "\n",
        "        # horizontaal\n",
        "        for r in range(6):\n",
        "            for c in range(4):\n",
        "                if all(board[r][c+i] == 1 for i in range(4)):\n",
        "                    return True\n",
        "\n",
        "        # verticaal\n",
        "        for r in range(3):\n",
        "            for c in range(7):\n",
        "                if all(board[r+i][c] == 1 for i in range(4)):\n",
        "                    return True\n",
        "\n",
        "        # diagonaal \\\n",
        "        for r in range(3):\n",
        "            for c in range(4):\n",
        "                if all(board[r+i][c+i] == 1 for i in range(4)):\n",
        "                    return True\n",
        "\n",
        "        # diagonaal /\n",
        "        for r in range(3, 6):\n",
        "            for c in range(4):\n",
        "                if all(board[r-i][c+i] == 1 for i in range(4)):\n",
        "                    return True\n",
        "\n",
        "        return False\n",
        "\n",
        "    def creates_threat(self, board, row, col):\n",
        "\n",
        "        temp = board.copy()\n",
        "        temp[row][col] = 1\n",
        "\n",
        "        # tel aantal 3-op-een-rij\n",
        "        count = 0\n",
        "\n",
        "        # horizontaal\n",
        "        for c in range(max(0, col-3), min(4, col+1)):\n",
        "            window = temp[row][c:c+4]\n",
        "            if np.sum(window) == 3:\n",
        "                count += 1\n",
        "\n",
        "        # verticaal\n",
        "        for r in range(max(0, row-3), min(3, row+1)):\n",
        "            window = [temp[r+i][col] for i in range(4)]\n",
        "            if sum(window) == 3:\n",
        "                count += 1\n",
        "\n",
        "        # diagonaal \\\n",
        "        for i in range(-3, 1):\n",
        "            coords = [(row+i+j, col+i+j) for j in range(4)]\n",
        "            if all(0 <= r < 6 and 0 <= c < 7 for r, c in coords):\n",
        "                window = [temp[r][c] for r, c in coords]\n",
        "                if sum(window) == 3:\n",
        "                    count += 1\n",
        "\n",
        "        # diagonaal /\n",
        "        for i in range(-3, 1):\n",
        "            coords = [(row-i-j, col+i+j) for j in range(4)]\n",
        "            if all(0 <= r < 6 and 0 <= c < 7 for r, c in coords):\n",
        "                window = [temp[r][c] for r, c in coords]\n",
        "                if sum(window) == 3:\n",
        "                    count += 1\n",
        "\n",
        "        return count > 0"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import random\n",
        "\n",
        "class MiddleFirstAgent:\n",
        "    def act(self, observation):\n",
        "        mask = observation[\"action_mask\"]\n",
        "        legal_moves = [i for i, m in enumerate(mask) if m == 1]\n",
        "\n",
        "        # Regel 1: middenkolom eerst\n",
        "        if 3 in legal_moves:\n",
        "            return 3\n",
        "\n",
        "        # Regel 2: anders random\n",
        "        return random.choice(legal_moves)"
      ],
      "metadata": {
        "id": "-Bi2mjbzd-y8"
      },
      "id": "-Bi2mjbzd-y8",
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "86801005",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "86801005",
        "outputId": "ffae0819-52c0-4fd4-9730-c702b1b4e292"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 3, 4, 5, 6]\n",
            "Jouw zet: 1\n",
            "AI speelt kolom: 3\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 3, 4, 5, 6]\n",
            "Jouw zet: 2\n",
            "AI speelt kolom: 3\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 3, 4, 5, 6]\n",
            "Jouw zet: 0\n",
            "AI speelt kolom: 3\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 3, 4, 5, 6]\n",
            "Jouw zet: 3\n",
            "AI speelt kolom: 3\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 3, 4, 5, 6]\n",
            "Jouw zet: 0\n",
            "AI speelt kolom: 3\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 4, 5, 6]\n",
            "Jouw zet: 0\n",
            "AI speelt kolom: 0\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 4, 5, 6]\n",
            "Jouw zet: 3\n",
            "❌ Ongeldige zet, kies uit: [0, 1, 2, 4, 5, 6]\n",
            "Jouw zet: 0\n",
            "AI speelt kolom: 1\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 4, 5, 6]\n",
            "Jouw zet: 1\n",
            "AI speelt kolom: 6\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 4, 5, 6]\n",
            "Jouw zet: 5\n",
            "AI speelt kolom: 6\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 4, 5, 6]\n",
            "Jouw zet: 5\n",
            "AI speelt kolom: 4\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 4, 5, 6]\n",
            "Jouw zet: 5\n",
            "AI speelt kolom: 6\n",
            "\n",
            "Jouw beurt!\n",
            "Kies kolom (0-6):  [0, 1, 2, 4, 5, 6]\n",
            "Jouw zet: 5\n"
          ]
        }
      ],
      "source": [
        "from pettingzoo.classic import connect_four_v3\n",
        "#from agents.blocking_agent import BlockingAgent\n",
        "\n",
        "env = connect_four_v3.env(render_mode=\"human\")\n",
        "env.reset()\n",
        "\n",
        "#agent_ai = BlockingAgent()\n",
        "agent_ai = MiddleFirstAgent()\n",
        "\n",
        "for agent in env.agent_iter():\n",
        "\n",
        "    observation, reward, termination, truncation, info = env.last()\n",
        "\n",
        "    if termination or truncation:\n",
        "        action = None\n",
        "    else:\n",
        "        mask = observation[\"action_mask\"]\n",
        "        legal_moves = [i for i, m in enumerate(mask) if m == 1]\n",
        "\n",
        "        if agent == \"player_0\":\n",
        "            # 👤 JIJ speelt\n",
        "            print(\"\\nJouw beurt!\")\n",
        "            print(\"Kies kolom (0-6): \", legal_moves)\n",
        "\n",
        "            while True:\n",
        "                try:\n",
        "                    action = int(input(\"Jouw zet: \"))\n",
        "                    if action in legal_moves:\n",
        "                        break\n",
        "                    else:\n",
        "                        print(\"❌ Ongeldige zet, kies uit:\", legal_moves)\n",
        "                except:\n",
        "                    print(\"❌ Voer een getal in\")\n",
        "\n",
        "        else:\n",
        "            # 🤖 Blocking Agent\n",
        "            action = agent_ai.act(observation)\n",
        "            print(f\"AI speelt kolom: {action}\")\n",
        "\n",
        "    env.step(action)\n",
        "\n",
        "env.close()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "03b76851",
      "metadata": {
        "id": "03b76851"
      },
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": ".venv",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.11.9"
    },
    "colab": {
      "provenance": []
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
